# Generated by Django 5.0.6 on 2024-05-25 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.PositiveSmallIntegerField()),
                ('color', models.CharField(choices=[('RED', 'red'), ('GREEN', 'green'), ('BLACK', 'black'), ('BLUE', 'blue'), ('PINK', 'pink'), ('ORANGE', 'orange')], max_length=16)),
                ('cargo', models.BooleanField(default=True)),
                ('cup_holder', models.BooleanField(default=False)),
                ('auto_type', models.CharField(choices=[('SPORT', 'sport'), ('VAN', 'van'), ('SUV', 'suv')], max_length=16)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=16)),
                ('birth_day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Wynajem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rezerwuj', to='rezerwuj.auto')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezerwuj.klient')),
            ],
        ),
    ]
